### ISSUE TITLE
Table S2 is missing in preprint

### ISSUE THREAD

**Issue by konstin** [flatironinstitute/deepblast#102]
i was just checking out https://www.biorxiv.org/content/10.1101/2022.07.25.501437v1.full.pdf and it seems that table S2 got lost:

![image](https://user-images.githubusercontent.com/6826232/183591006-9db7bf92-7cf8-44b3-8322-718b5af5d6d2.png)

**Comment by mortonjt** [comment]
HI @konstin we'll add supplemental tables to biorvix shortly. Thanks.

**Comment by mortonjt** [comment]
Hi @konstin updated tables can be found at Biorvix : https://www.biorxiv.org/content/10.1101/2022.07.25.501437v2.supplementary-material

**Comment by konstin** [comment]
thanks!
