### ISSUE TITLE
File not found (deleted tm-vec repository)

### ISSUE THREAD

**Issue by IrumHu** [flatironinstitute/deepblast#106]
In the older tm-vec repository ,
For the file `tm-vec/ipynb/repo_TM.ipynb`, can you please provide the following local checkpoint and the config file
1. tm_vec_model_cpnt `/mnt/home/thamamsy/ceph/deepblast/models/transformer_lr0.0001_dmodel1024_nlayer2_datasample_45_thresh_300_pairs_in_folds_included_23M_normal_tmax/checkpoints/last.ckpt`
2. tm_vec_model_config `/mnt/home/thamamsy/ceph/deepblast/models/transformer_lr0.0001_dmodel1024_nlayer2_datasample_45_thresh_300_pairs_in_folds_included_23M_normal_tmax/params.json`

**Comment by tymor22** [comment]
We will update the ipynbs but the checkpoints and config files are all downloadable from the read me.
