### ISSUE TITLE
Make DeepBLAST CPU compatible

### ISSUE THREAD

**Issue by mortonjt** [flatironinstitute/deepblast#109]
We do have a [numba version of the aligner](https://github.com/flatironinstitute/deepblast/blob/master/deepblast/nw.py) that is CPU compatible, but for some reason it isn't working.

- [x] Update the [NW unittests](https://github.com/flatironinstitute/deepblast/blob/master/deepblast/tests/test_nw.py) to use numba instead 
- [ ] Update the [alignment code](https://github.com/flatironinstitute/deepblast/blob/master/deepblast/alignment.py#L63) to optionally use the CPU version.

**Comment by blackwer** [comment]
NW unittests already use numba, so I've marked that off. I'll work on the alignment code now.
