### ISSUE TITLE
No 'LightningAligner' can be import

### ISSUE THREAD

**Issue by Ravy-LFL** [flatironinstitute/deepblast#131]
Dear,

I'm going through this issue where i can not import 'LightningAligner' from trainer.py. Indeed 'LightningAligner' do not exist in trainer.py. How can i fix this ? Is this normal ? Here is the error :

`Traceback (most recent call last):
  File "/path/bio_embeddings", line 6, in <module>
    from bio_embeddings.utilities.cli import main
  File "/paths/cli.py", line 6, in <module>
    from bio_embeddings.utilities.pipeline import parse_config_file_and_execute_run
  File "/path/pipeline.py", line 40, in <module>
    from bio_embeddings.align.pipeline import run as run_align
  File "/path/bio_embeddings/align/__init__.py", line 1, in <module>
    from .deepblast import deepblast_align
  File "/path/align/deepblast.py", line 8, in <module>
    from deepblast.trainer import LightningAligner
ImportError: cannot import name 'LightningAligner' from 'deepblast.trainer' (/path/trainer.py)`

Thanks alot

**Comment by Ravy-LFL** [comment]
seems to be better thanks

**Comment by konstin** [comment]
> There could be merits to having bio_embeddings updated. Thoughts @konstin ?

i'm not working on bio_embeddings anymore

**Comment by mortonjt** [comment]
Thanks, feel free to CC someone who is continuing maintainence on
bio_embeddings

**Comment by mortonjt** [comment]
CC @sacdallago

**Comment by mortonjt** [comment]
Hi @Ravy-LFL I'm going to close this issue since it seems resolved -- but feel free to reopen if there are outstanding issues.
