### ISSUE TITLE
cannot import name 'LightningAligner' from 'deepblast.trainer'

### ISSUE THREAD

**Issue by meltzj** [flatironinstitute/deepblast#138]
Hi there,

I tested to see if the deepblast-search script was working and when i ran 'deepblast-search -h' i got the following error

Traceback (most recent call last):
  File "/srv/scratch/z5116142/miniconda3/envs/deepblast/bin/deepblast-search", line 9, in <module>
    from deepblast.trainer import LightningAligner
ImportError: cannot import name 'LightningAligner' from 'deepblast.trainer' (/srv/scratch/z5116142/miniconda3/envs/deepblast/lib/python3.9/site-packages/deepblast/trainer.py)

I know someone had a similar error using bio_embeddings however I have installed through pip install using the pip requirements file in a new conda environment and am running it on HPC.

**Comment by mortonjt** [comment]
Hi, can you print out the version? That looks like it is from a previous
release

**Comment by mortonjt** [comment]
Closing since this is from a previous release
