### ISSUE TITLE
DeepBLAST issue with model load

### ISSUE THREAD

**Issue by mortonjt** [flatironinstitute/deepblast#139]
https://github.com/tymor22/tm-vec/issues/24

@blackwer

**Comment by CrazyHsu** [comment]
Hi, Jamie, has this issue been fixed?

**Comment by mortonjt** [comment]
I’m not seeing this error on my end. But we did update the readme to
download protT5 locally, so you can try again

**Comment by mortonjt** [comment]
Hi @CrazyHsu thanks for your patience.  I have some time to take a deeper look into this.  Feel free to test out the updated instructions and `load_model` method.
