### ISSUE TITLE
Deepblast model confusion 

### ISSUE THREAD

**Issue by wangy9711** [flatironinstitute/deepblast#149]
Regarding the pretrained DeepBLAST model, three download links are provided in the repository:

1. https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-l8.ckpt (In Readme.md)
2. https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-v3.ckpt (In Wiki)
3. https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-pt-l8.ckpt (In Wiki)

In fact, only the second model is working. When using the other two models, tmvec-serach with alignment cannot be run normally.
I hope the other two download addresses can be removed to avoid misunderstandings.

Thanks.

**Comment by mortonjt** [comment]
Hi, see the readme https://figshare.com/articles/dataset/TMvec_DeepBLAST_models/25810099
The model links have been updated
