### ISSUE TITLE
Where is the structure alignment output?

### ISSUE THREAD

**Issue by echovv** [flatironinstitute/deepblast#150]
Hi, I am a newer in protein alignment.
I just wonder as you mentioned in the paper, TM-Vec+DeepBlast can produce a Sequence alignment output and Structure alignment out also.
Now, I follow the guidance in Wiki, and successfully get the test.npy, alignment.txt, tabular.txt. I think Sequence alignment information is saved in alignment.txt. And where is the structure alignment output or whether it can directly produce a PDB file for protein structure visualization? And what does the number array in test.npy mean? 

Thanks!
ziwei

**Comment by Aurorajwy** [comment]
hi， can you tell me how long did it take you to get the result file, were there any intermediate files or error messages?

**Comment by mortonjt** [comment]
Hi, correct, the structural alignment is under `alignment.txt` -- and it is represented as a linear sequence alignment (just like TMalign).

We do not support producing PBD files or protein structural alignment visualizations, but there should not be an obstacle to that (if you can generate these visualizations with sequence alignments, you can generate them with the DeepBLAST alignments).

@Aurorajwy try a small test file (with <5 sequences) first -- it should take on the order of minutes to run
