### ISSUE TITLE
After entering the command line, the program keeps running without any result.

### ISSUE THREAD

**Issue by Aurorajwy** [flatironinstitute/deepblast#152]
i can not get the result files when run the tm-vec search for two days, the device is gpu.

**Comment by mortonjt** [comment]
Hi, you'll need to give more detail on what you are running. How many
sequences are you inputting? And did you try the tutorial?

**Comment by Aurorajwy** [comment]
I used just one sequence for testing. I solved the problem while using CPU. But there is one more question I would like to ask, what is the data contained in the .npy file that I get. How to output the sequences after comparison  by deepblast in the results?

**Comment by mortonjt** [comment]
Hi, those contain the vector embeddings, which can be used for downstream
ML / search

**Comment by Aurorajwy** [comment]
Thank you very much for your answer. I would also like to ask, following the tutorial, I created a bagel.fa to do a deepblast with itself, why can't I generate alignments files, the result shows as no valid comparison. following：
![image](https://github.com/flatironinstitute/deepblast/assets/124338511/a8dd1f11-dd30-4389-97c4-682f9fd80048)

**Comment by mortonjt** [comment]
Hmm, there should be alignments. Can you paste the command that you used
and the full error message? You may need to specify the alignment flag.
I’ll try to reproduce the error

**Comment by Aurorajwy** [comment]
the command is :tmvec-search --query bagel.fasta --tm-vec-model tm_vec_cath_model.ckpt --tm-vec-config tm_vec_cath_model_params.json --database bagel_database/db.npy --metadata bagel_database/meta.npy --database-fasta bagel.fasta --database-faidx bagel.fai --deepblast-model deepblast-v3.ckpt --k-nearest-neighbors 1 --output-format alignment --output alignments.txt --output-embeddings test3.npy
the error massage is :
![image](https://github.com/flatironinstitute/deepblast/assets/124338511/5af7ebc6-60ee-440f-ad98-2348aba2ac3a)

**Comment by Aurorajwy** [comment]
Is it possible  the command inputed incorrectly? @mortonjt

**Comment by Aurorajwy** [comment]
hi, i tried deepblast again. I change the model of deepblast to deepblast-pt-18.ckpt according to  the tutorial, I re-run the deepblast command, but it produces the following error. 
![image](https://github.com/flatironinstitute/deepblast/assets/124338511/df9828be-a538-4398-9a93-e7341bc3f3a2)
hope for you reply  this error.

**Comment by mortonjt** [comment]
Hi, I've rerun the command on my end, had to change a few things to match the tutorial files (and to make it run within 1 hour)

```
head -n 4 bagel.fa > query.fa

tmvec-search --query query.fa --tm-vec-model tm_vec_cath_model.ckpt --tm-vec-config tm_vec_cath_model_params.json --database bagel_database/db.npy --metadata bagel_database/meta.npy --database-fasta bagel.fa --deepblast-model deepblast-v3.ckpt --k-nearest-neighbors 1 --output-format alignment --output alignments.txt --output-embeddings test3.npy
```
The alignments were generated as follows
```
Tricyclic_peptide_MS-271  CLGVGSCNNFAGCGYAIVCFW
Tricyclic_peptide_MS-271  CLGVGSCNNFAGCGYAIVCFW

Capistruin  MVRLLAKLLRSTIHGSNGVSLDAVSSTHGTPGFQTPDARVISRFGFN
Capistruin  MVRLLAKLLRSTIHGSNGVSLDAVSSTHGTPGFQTPDARVISRFGFN
```
I'm not sure what issue you are running into.  It would help to output the installed pip and conda packages `pip freeze > requirements.txt` and `conda env export > env.yaml`
