### ISSUE TITLE
Pretraind model download

### ISSUE THREAD

**Issue by gbrsales** [flatironinstitute/deepblast#160]
Hi,

I'm trying to download the weights of the pre-built model as described in the [Searching proteins](https://github.com/flatironinstitute/deepblast/wiki/Searching-proteins) guide. Unfortunately, wget fails as follows:

```
wget https://users.flatironinstitute.org/thamamsy/public_www/tm_vec_cath_model.ckpt
--2024-05-13 13:55:58--  https://users.flatironinstitute.org/thamamsy/public_www/tm_vec_cath_model.ckpt
Resolving users.flatironinstitute.org (users.flatironinstitute.org)... 144.121.86.48
Connecting to users.flatironinstitute.org (users.flatironinstitute.org)|144.121.86.48|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /~thamamsy/tm_vec_cath_model.ckpt [following]
--2024-05-13 13:55:59--  https://users.flatironinstitute.org/~thamamsy/tm_vec_cath_model.ckpt
Reusing existing connection to users.flatironinstitute.org:443.
HTTP request sent, awaiting response... 403 Forbidden
2024-05-13 13:55:59 ERROR 403: Forbidden.
```

Do you have an alternative download link or method I could try?

**Comment by mortonjt** [comment]
Hi thanks. We are currently shuffling around datasets in preparation for the new release.
In the meantime the TMvec and DeepBLAST checkpoints can be found on fig share 
https://figshare.com/articles/dataset/TMvec_DeepBLAST_models/25810099

**Comment by gbrsales** [comment]
The download from figshare works perfectly.

Thanks!

**Comment by gbrsales** [comment]
Hi @mortonjt,

I'm having another download problem. This time I'm trying to download the [available databases](https://github.com/flatironinstitute/deepblast/wiki/Available-databases). Neither CATH S100 nor Swissprot are available, due to a 403 error similar to the one I reported before.

I also tried to build my own database from Swissprot, but ran out of memory as reported in #141 .

It looks like downloading a pre-built database is the only way to go. Could you please provide some updated links?

Thanks

**Comment by mortonjt** [comment]
Hi, I've uploaded the Swissprot database here : https://zenodo.org/deposit/11199459
Sharing the protrans embeddings is currently difficult, since zenodo timing out. More to come.

**Comment by gbrsales** [comment]
Hi, thanks for the upload! Zenodo complains, however, that "You do not have sufficient permissions to view this page."

**Comment by mortonjt** [comment]
That was a typo above, it should be `records` give it a shot now

**Comment by gbrsales** [comment]
Works now, thanks!
