### ISSUE TITLE
Model download link failed

### ISSUE THREAD

**Issue by yuanwenguang666** [flatironinstitute/deepblast#161]
Dear the author: 

Hello!
I want to test vm-vec and deepblast. However, this link https://users.flatironinstitute.org/thamamsy/public_www/tm_vec_swiss_model.ckpt returns a 404 error. Additionally, the link mentioned in this GitHub issue https://github.com/flatironinstitute/deepblast/issues/160, https://figshare.com/articles/dataset/TMvec_DeepBLAST_models/25810099, is also not accessible. How can I download this pre-trained model?
Thanks!

all the best!
wenguang

**Comment by yuanwenguang666** [comment]
Sorry for my mistake, I have download the model.

**Comment by mortonjt** [comment]
Hi, see the README https://figshare.com/articles/dataset/TMvec_DeepBLAST_models/25810099
