### ISSUE TITLE
Error While Downloading DeepBLAST Model and Database

### ISSUE THREAD

**Issue by khatrics16** [flatironinstitute/deepblast#162]
While trying to install the DeepBLAST model and the associated database using the provided wget commands, I encountered an error indicating that the model file could not be found. Below are the steps I followed and the resulting error message:

Attempted to download the DeepBLAST model using the following command:
wget https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-v3.ckpt

Error Message:
--2024-07-25 14:03:39--  https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-v3.ckpt
Resolving users.flatironinstitute.org (users.flatironinstitute.org)... 144.121.86.48
Connecting to users.flatironinstitute.org (users.flatironinstitute.org)|144.121.86.48|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /~jmorton/deepblast-public-data/checkpoints/deepblast-v3.ckpt [following]
--2024-07-25 14:03:39--  https://users.flatironinstitute.org/~jmorton/deepblast-public-data/checkpoints/deepblast-v3.ckpt
Reusing existing connection to users.flatironinstitute.org:443.
HTTP request sent, awaiting response... 404 Not Found
2024-07-25 14:03:39 ERROR 404: Not Found.

It appears that the file might have been moved or the URL might be incorrect.

Could you please verify the location of the DeepBLAST model file and update the download URL if it has changed?

**Comment by mortonjt** [comment]
Hi, I'm not sure where you are seeing these wget instructions. The README has been updated with the latest checkpoints
I'll link them here again https://figshare.com/articles/dataset/TMvec_DeepBLAST_models/25810099
