### ISSUE TITLE
link for downloading deepblast checkpoints in wiki returns a 404

### ISSUE THREAD

**Issue by aryankeluskar** [flatironinstitute/deepblast#164]
![image](https://github.com/user-attachments/assets/a86c96a0-9420-4992-a66f-28fb182cf403)

In the [Aligning Proteins wiki article](https://github.com/flatironinstitute/deepblast/wiki/Aligning-proteins), it is recommended to download the model checkpoints from the following link: https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-v3.ckpt

However, this link currently results in a 404 Error. As an alternative, I tried accessing the checkpoints through a link provided in the README, and it worked: https://figshare.com/articles/dataset/TMvec_DeepBLAST_models/25810099?file=46296316

Could the wiki be updated to reflect the working download link?

**Comment by mortonjt** [comment]
Updated, thanks!
