### ISSUE TITLE
Comparison between two sequences

### ISSUE THREAD

**Issue by AIM132** [flatironinstitute/deepblast#167]
Can it specify two sequences for comparison and get the predicted value of TMScore of the corresponding structures of these two sequences?Thanks

**Comment by AIM132** [comment]
I hope TMVec can support specifying two sequences as input and then outputting the predicted TMscore, which will facilitate a small number of pairwise comparisons.

**Comment by mortonjt** [comment]
Yes it can, but it may require running the python code in the tmvec repo

**Comment by AIM132** [comment]
Thank you. I'll give it a try

**Comment by GodPCWANG** [comment]
Hello，have you resolved this issue?

**Comment by mortonjt** [comment]
https://github.com/tymor22/tm-vec/blob/master/tm_vec/tm_vec_utils.py#L45-L49

Its all in the source code, although documentation needs some work.
