### ISSUE TITLE
deepblast-search fails with AttributeError: 'function' object has no attribute 'score'

### ISSUE THREAD

**Issue by konstin** [flatironinstitute/deepblast#86]
Hi,

I'm interested in using DeepBLAST as part of a search workflow, so I tried to run `scripts/deepblast-search`, but unfortunately it crashes:

```
$ python scripts/deepblast-search --query-fasta QUERY.fasta --db-fasta DB.fasta --load-from-checkpoint deepblast-lstm4x.pt --output-file output
args Namespace(batch_size=10, db_fasta='DB.fasta', gpu=None, load_from_checkpoint='deepblast-lstm4x.pt', num_workers=1, output_file='output', query_fasta='QUERY.fasta')
0it [00:09, ?it/s]
Traceback (most recent call last):
  File "scripts/deepblast-search", line 63, in <module>
    main(hparams)
  File "scripts/deepblast-search", line 38, in main
    A = model.align.score(seqs, order)
AttributeError: 'function' object has no attribute 'score'
```

Steps to reproduce (crashes both with and without a GPU):

```bash
git clone https://github.com/flatironinstitute/deepblast
cd deepblact
virtualenv .venv
. .venv/bin/activate
pip install -e .
pip install biopython
wget https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-lstm4x.pt
wget https://raw.githubusercontent.com/soedinglab/MMseqs2/master/examples/QUERY.fasta
wget https://raw.githubusercontent.com/soedinglab/MMseqs2/master/examples/DB.fasta
python scripts/deepblast-search --query-fasta QUERY.fasta --db-fasta DB.fasta --load-from-checkpoint deepblast-lstm4x.pt --output-file output
```

**Comment by mortonjt** [comment]
Hi @konstin thank you for your interest.  This is a known outstanding bug - the search capabilities aren't quite there yet :(

We have an outstanding pull request : https://github.com/flatironinstitute/deepblast/pull/78
That will at least allow you to search against sequences that are less than 2k residues.

**Comment by konstin** [comment]
Thanks for the quick response!

Do you have an example of how to get alignment scores outside of the `deepblast-search`? I tried the following two but neither worked (`x` and `y` are `str`, `model` is `deepblast-lstm4x.pt`:

```python
dbtoks = torch.Tensor(UniprotTokenizer()(str.encode(x))).long()
qtoks = torch.Tensor(UniprotTokenizer()(str.encode(y))).long()
model.score(dbtoks, qtoks)
```

```python
dbtoks = torch.Tensor(UniprotTokenizer()(str.encode(x))).long()
qtoks = torch.Tensor(UniprotTokenizer()(str.encode(y))).long()
seq, order = pack_sequences(dbtoks, qtoks)
seq = seq.to(torch.device("cuda"))
model.score(seq, order)
```

**Comment by CeciLyu** [comment]
Hi tm-vec team,

I would like to check if there's any update on predicting the tm-score at scale. I have tried the tmvec-align-search.py script, but I got the same error as mentioned above. Since it's been  more than a year ago, I would like to know if this has been fixed?

Thanks

**Comment by mortonjt** [comment]
Hi @konstin and @CeciLyu , we have deprecated deepblast-search in favor of TM-vec. See https://github.com/flatironinstitute/deepblast/issues/127 and the updated wiki
