### ISSUE TITLE
Weights can't be downloaded with python (User-Agent blocked)

### ISSUE THREAD

**Issue by konstin** [flatironinstitute/deepblast#89]
The webserver blocks python-urllib as user agent for downloading the weights:

```
$ curl -H "User-Agent: Python-urllib/3.8" https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-lstm4x.pt
error code: 1010
$ curl -H "User-Agent: not-python/3.8" https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-lstm4x.pt
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```

It's not hard to fake a different user agent, but I don't think that the standard python snippet for downloading the weights should be blocked.

**Comment by mortonjt** [comment]
I'm a little confused why this error is occurring ...

Does wget work for you?  I'm able to download with the following command

wget
https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-lstm4x.pt

**Comment by konstin** [comment]
The problem occurs when using python, curl was just for demonstrating that the problem is the user agent:

```python
from urllib import request
request.urlretrieve("https://users.flatironinstitute.org/jmorton/public_www/deepblast-public-data/checkpoints/deepblast-lstm4x.pt", filename="deepblast-lstm4x.pt")
```

What I believe that is happening is that the webserver is configured to specifically block python clients. This is sometimes done to avoid scraping, even though in my eyes this makes no sense as you can trivially circumvent it by setting a fake user agent (e.g. the user agent of a browser)

**Comment by mortonjt** [comment]
Hi @konstin , are you still running into this problem?  I'd like to close this issue if so

**Comment by konstin** [comment]
no idea, i'm using something different now
