### ISSUE TITLE
How to solve the following problems?

### ISSUE THREAD

**Issue by mazhichong** [flatironinstitute/deepblast#97]
Hello，I encountered the following problem when running the code. How can I solve it?
1.I am running deepblast-train with an error:FileNotFoundError: [Errno 2] File b'VALID_PAIRS' does not exist: b'VALID_PAIRS'。
2.I am running deepblast-evaluate with an error:FileNotFoundErro： deepblast-evaluate: error: the following arguments are required: --train-pairs, --test-pairs, --valid-pairs, -o/--output-directory
3..I am running tm with an error:FileNotFoundErro：ValueError: invalid literal for int() with base 10: 'TEST_PAIRS'

**Comment by mortonjt** [comment]
You need to specify train / test / validate files if you are going to train or evaluate deepblast.
I'll update the documentation shortly.  Also note that over the next few days, we are going to update the dependencies, so hang tight.

**Comment by mortonjt** [comment]
Hi, @mazhichong deepblast-evaluate is now deprecated. See https://github.com/flatironinstitute/deepblast/issues/127
