### ISSUE TITLE
Loading a pretrained model

### ISSUE THREAD

**Issue by OliviaViessmann** [flatironinstitute/deepblast#99]
Hello, 
I am trying to run the "Loading the model" example code you provided on the github page. I am trying to run the example using the downloadable model "deepblast-lstm4x.pt":

#Load the pretrained model
model = LightningAligner.load_from_checkpoint('/home/deepblast/deepblast-lstm4x.pt')

But the LigningAligner cannot read that model and I get an AttributeError. 

What is the correct way of running this code example? How do I call your model correctly?
Thanks
Olivia

**Comment by mortonjt** [comment]
Hi @OliviaViessmann, we haven't had issues loading the models lately.  Could you give the full error message?  In addition to your software versions?  Also double check to make sure that your pytorch version is up to date.

**Comment by OliviaViessmann** [comment]
Thanks for the quick feedback. Here is the full stack trace:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [11], in <cell line: 2>()
      1 # Load the pretrained model
----> 2 model = LightningAligner.load_from_checkpoint('/home/pi-user/deepblast/deepblast-lstm4x.pt')
      4 # Load on GPU (if you want)
      5 #model = model.cuda()
      6 
      7 # Obtain hard alignment from the raw sequences
      8 x = 'IGKEEIQQRLAQFVDHWKELKQLAAARGQRLEESLEYQQFVANVEEEEAWINEKMTLVASED'

File ~/miniconda3/envs/piai/lib/python3.8/site-packages/pytorch_lightning/core/saving.py:161, in ModelIO.load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, strict, **kwargs)
    158 # override the hparams with values that were passed in
    159 checkpoint[cls.CHECKPOINT_HYPER_PARAMS_KEY].update(kwargs)
--> 161 model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
    162 return model

File ~/miniconda3/envs/piai/lib/python3.8/site-packages/pytorch_lightning/core/saving.py:203, in ModelIO._load_model_state(cls, checkpoint, strict, **cls_kwargs_new)
    199 if not cls_spec.varkw:
    200     # filter kwargs according to class init unless it allows any argument via kwargs
    201     _cls_kwargs = {k: v for k, v in _cls_kwargs.items() if k in cls_init_args_name}
--> 203 model = cls(**_cls_kwargs)
    205 # give model a chance to load something
    206 model.on_load_checkpoint(checkpoint)

File ~/miniconda3/envs/piai/lib/python3.8/site-packages/deepblast/trainer.py:29, in LightningAligner.__init__(self, args)
     27 super(LightningAligner, self).__init__()
     28 self.tokenizer = UniprotTokenizer(pad_ends=False)
---> 29 self.hparams = args
     30 self.initialize_aligner()
     31 if self.hparams.loss == 'sse':

File ~/miniconda3/envs/piai/lib/python3.8/site-packages/torch/nn/modules/module.py:1233, in Module.__setattr__(self, name, value)
   1231     buffers[name] = value
   1232 else:
-> 1233     object.__setattr__(self, name, value)

AttributeError: can't set attribute

**Comment by OliviaViessmann** [comment]
And my version of torch ist
1.11.0

**Comment by mortonjt** [comment]
hmm that looks like a pytorch-lightening error -- what version is that?

**Comment by OliviaViessmann** [comment]
It's
1.6.3

**Comment by OliviaViessmann** [comment]
Which version of pytorch-lightning are you using for DeepBlast?

**Comment by mortonjt** [comment]
Hi, @OliviaViessmann so your error hints that you are using an old version of deepblast. I'm assuming that you ran `pip install deepblast` correct?  Installing the development branch with the latest versions `pip install git+https://github.com/flatironinstitute/deepblast.git` may address these issues.

There are a couple of changes that currently being incorporated, so a new release is on the way.

**Comment by OliviaViessmann** [comment]
Hi @mortonjt 
thanks for the assistance with this issue. I `pip uninstall deepblast` and ran `pip install git+https://github.com/flatironinstitute/deepblast.git`. I am still getting the same error :(
